# -*- coding: utf-8 -*-
"""Exercise1_Jan 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEtiRSLio7SgVOJSgAtcuDqOeUoS837h

## Step 1 import package
"""

import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt

"""## Step 2: connect to google drive"""

drive.mount('/content/gdrive',force_remount = True)

"""## Step 3: Read file"""

df = pd.read_csv("/content/gdrive/MyDrive/JPM.csv")

"""## Step 4: Data Cleaning"""

df.head()

plt.figure(figsize = (10,5))
plt.plot(df.Close)
plt.title("JPM stock price")
plt.xlabel("INDEX")
plt.ylabel("price")
plt.show()